spring:
  application:
    name: smartcampus
    security:
      jwt:
        # Can be generated online
        secret-key: 5fadbfed784644f631bb0bdb7a36c9e30435e21cd51ca77c35b00adafd296970
        expiration: 8640000

  datasource:
    url: jdbc:mysql://localhost:3306/smartcampus
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  jackson:
    serialization:
      write-dates-as-timestamps: false


