spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: TRACE

springdoc:
  default-produces-media-type: application/json
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui


