spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

Springdoc:
  default-produces-media-type: application/json
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui