spring:
  application:
    name: smartcampus
    security:
      jwt:
        # Can be generated online
        secret-key: 5fadbfed784644f631bb0bdb7a36c9e30435e21cd51ca77c35b00adafd296970
        expiration: 8640000

  datasource:
    url: jdbc:mysql://localhost:3306/smartcampus
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true